name: Print Message

on:
  push:
    branches:
      - main

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: python hello_world.py
